### PR TITLE
Port change back to vflow.

### PR DESCRIPTION
**Pull request by hanlhe**
### Check List

[Describe your test plan - use the checklist below as a guideline]

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### Reviewers

@maarumug @tpatward @supreeth-t

### CODE REVIEW

**Comment by hanlhe** [comment]
LGTM

**Comment by tetbuild** [comment]
## LGTMs
by hanlhe

|G|File|Owner|
|---|---|---|
✓|*Makefile*|
✓|*ipfix/basiclist.go*|
✓|*ipfix/decoder.go*|
✓|*ipfix/marshal.go*|
✓|*ipfix/marshal_test.go*|
✓|*netflow/v9/decoder.go*|
✓|*netflow/v9/decoder_test.go*|
✓|*netflow/v9/marshal.go*|
✓|*netflow/v9/memcache.go*|
✓|*reader/reader.go*|
✓|*reader/reader_test.go*|

**Comment by vkorpolu** [comment]
lgtm

**Comment by vkorpolu** [comment]
lgtm

**Comment by vkorpolu** [comment]
lgtm

**Pull request merged**
